### ISSUE TITLE
NextExpectedMsgSeqNum not working

### ISSUE THREAD

**Issue by WeirdWang** [quickfix/quickfix#146]
I'm using quickfix to connect Exchange directly with FIX version 5.0, there is one scenario is when network down and some message will be lost, so Exchange will send back logon message with NextExpectedMsgSeqNum,  seems quickfix didn't handle it, not sending lost message with the NextExpectedMsgSeqNum from Exchange but continue current sequence number, 

is this a known issue and are we going to fix this problem?

**Comment by yajnasteju** [comment]
This should be the flow when connection lost to exchange  : 

1. Keep a track of the last received message from exchange and Send Resend Request to exchange in case the logon message sequence number is not as expected.
2. The exchange will send all the requested packets for you to reconcile.

Please note: You **cannot frame a resend message and send to server** , because internal flags will fail to dispatch the message to the server. 

Most probably your server might be sending a sequence reset message , handle your logic to  setNextTargetMsgSeqNum(atoi(seq.c_str())) , so that quickfix will detect the gap automatically and fire a  resend message .

It will be helpful if you post the sequence flow of your messages .

**Note:** I have implemented this solution for FIX 4.4 , but i am not sure whether it will work on 5.0

**Comment by WeirdWang** [comment]
Thanks for your reply. Actually the issue is not in Exchange side, it is in QuickFix side. When Exchange sending logon message with NextExpectedMesssageSeqNum, it is expecting broker sending the message from that seq number to the latest one, but seems quickFix didnt handle it at all.

Now I did some logic change as above - to send all message(if need) from the NextExpectedMessageSeqNumber to Exchange, and it is working fine
