### ISSUE TITLE
How can I guarantee that a subscribe message was sent to the specific connection?

### ISSUE THREAD

**Issue by leleftheriades** [quickfix/quickfix#270]
We came across a problem we can not figure out how to solve:

We have a separate thread deciding on what instruments to subscribe or unsubscribe for receiving market data. We are configured to reset the sequence numbers on a new connection.

The question is, what would happen while we are sending the instruments one-by-one from the business logic thread, a logout/logon happens? Will that mean that some of the instruments were sent to the old session and some of it to the new session? Is there a way that we can make it such that any send we are intending for the old session is not sent to the new one?

Note that I am using the word session to indicate a connection session, since the state is reset every time a connection is made

**Comment by quickfix** [comment]
You need to monitor logons and logoffs and resend any subscriptions when you receive a new logon.

Generally you want a certain set of subscriptions regardless of the state of the session. When there is a reset, you would just want to send everything you currently want to be subscribed to. 

I’m not sure what you mean by intended for the old vs new. Are you saying when the session gets reset you don’t want to renew the old subscriptions? Or you are just concerned you might be sending duplicate subscriptions?

**Comment by leleftheriades** [comment]
I am concerned about sending duplicate subscriptions

**Comment by quickfix** [comment]
You should be able to accurately track what subscriptions you have sent since the last logon. Is there a particular scenario where you suspect there is a race condition?

**Comment by ageorgallides** [comment]
The ABBA deadlock can happen as follows because onLogout and setSymbols lock the mutexes in the opposite order:

    // QuickfixThread
    lock(quickfix_mutex);
    onLogout()
    {
        lock(state_mutex);
        state = DISCONNECTED;
    }

    // ApplicationThread
    setSymbols(set<string> symbols)
    {
        lock(state_mutex);
        foreach(symbol in symbols)
        {
            sendMarketDataRequest(symbol);
            // eventually calls fixSession.sendToTarget() which calls lock(quickfix_mutex)
        }
    }

To avoid the ABBA problem, setSymbols MUST unlock the state_mutex before calling sendMarketDataRequest as shown below:

    // QuickfixThread
    lock(quickfix_mutex);
    onLogout()
    {
        lock(state_mutex);
        state = DISCONNECTED;
    }

    // QuickfixThread
    onLogon()
    {
        lock(state_mutex);
        state = CONNECTED;
        foreach(symbol in requestedSymbols) sendMarketDataRequest(symbol);
    }

    // ApplicationThread
    setSymbols(set<string> symbols)
    {
        lock(state_mutex);
        requestedSymbols = symbols;

        if(state != CONNECTED) return;
        unlock(state_mutex);
        foreach(symbol in requestedSymbols)
        {
            sendMarketDataRequest(symbol);
        }
    }

POTENTIAL RACE CONDITION SCENARIO:
1. Let's assume that QuickfixThread called onLogon() and state = CONNECTED. 
2. Then the ApplicationThread calls setSymbols(), setSymbols finds state == CONNECTED and unlocks the state_mutex (here the ApplicationThread yields and QuickfixThread is about to take over)
3. The network connection drops, and the QuickfixThread calls onLogout()
4. The network connection re-establishes, and the QuickfixThread calls onLogon() which subscribes to requestedSymbols (here the QuickfixThread yields and ApplicationThread is about to take over)
5. Then the Applicationthread continues and subscribes to requestedSymbols

Thus, subscriptions are sent out twice, in step 4 and step 5.

QUESTIONS:
1. Does the machine state of Quickfix allows the above scenario to happen?
2. Does the machine state of Quickfix guarantee that onLogout() cannot be called while in onLogon() and vice versa?

**Comment by leleftheriades** [comment]
I can not find a scenario in which I can know if the request was sent to the old or the new connection.

---

Quickfix thread:

    void onLogout(){
	    sentSubscriptions.clear();
    }


Business Logic thread:

    void subscribeToSymbols(){
        if (sendToTarget(SymbolA)){
	         sentSubscriptions.Add("SymbolA");
	    }
	    if (sendToTarget(SymbolB)){
    	    Sleep(1000); //Here connection drops and reconnects
	    	sentSubscriptions.Add("SymbolB");
	    }
    }


Here symbol B will be considered sent to the new connection when it has not.
Note:  I can not use a mutex to include both the sendToTarget and addition to the list without causing a deadlock between send to target and onLogout. I thought of several alternative implementations, but I always end up not knowing where something was sent. 
On a second note, I believe that the library allows sending data from a few instructions before the onLogon event is sent, that's why I believe clearing the sentSubscriptions in onLogon will be too late since some requests may have been sent to the new connection already.
