### ISSUE TITLE
my message cracker(fromAdmin and fromApp) does not get resent messages.

### ISSUE THREAD

**Issue by SDRLurker** [quickfix/quickfix#391]
I am writing an initiator python application. When I send a resend request with BeginSeqNo(7)=1 and EndSeqNo(16)=10 to the server, these messages do not seem to be processed by my message cracker.

[2022-04-12 09:34:59,757] > [SEND] 09:34:59 toAdmin message '8=FIXT.1.1|9=74|**35=2**|34=3|49=E-DAILYFIX1|52=20220412-00:34:59.757|56=TPICAP-UAT|**7=1|16=10**|10=175|' from session 'FIXT.1.1:E-DAILYFIX1->TPICAP-UAT'.

Both fromAdmin and fromApp do not get these messages. So is there a way for me to tell QuickFIX that I want to see these messages?

**Comment by orenmnero** [comment]
There is not.

First at the protocol level, the FIX spec will never resend admin messages. A GapFill message will be sent in its place, so there is no way for QuickFIX to receive those messages again.

As for application messages, quickfix will block them from being passed to the callback if they have already been processed. If you received a fromApp callback and did not through an exception, it is agreed that the message has been processed and will never make it back into the queue. Otherwise sever bugs could happen if applications are unaware that a resent message could make it into the callback by processing say executions multiple times if they don't check the resend status. The fix engine takes care of this and guarantees exactly one callback per message.

It is also not recommended to directly send resend requests. It is the session's job to determine when that is necessary via sequence number gaps.
