### ISSUE TITLE
Is it possible to overload the functions that writes the log?

### ISSUE THREAD

**Issue by FabioNevesRezende** [quickfix/quickfix#416]
I'm trying to modify the logged message in the session in order to change some data on the fields before it gets logged into the .messages.log file and I found this class FIX::FileLogFactory that was meant to do this but I couldn't manage to actually change the behavior of the logging process since this class only exposes one method called create/destroy, the FIX::Log returned also couldn't have the onIncoming onOutgoing and onEvent overloaded.. so how do to this task?thanks in advance

**Comment by McLeodD** [comment]
I think your message should be on StackOverflow rather than GitHub. This is not an issue of quickfix...

To answer your question, however, you simply need to create a custom Factory and a custom Logger (FIX::Log):
You can take example on how the ScreenLogFactory is implemented here:
https://github.com/quickfix/quickfix/blob/12ae2153f6e91c9bf30cc53e83742d983eec66ff/src/C%2B%2B/Log.h#L56

And the example on how ScreenLog is implemented here:
https://github.com/quickfix/quickfix/blob/12ae2153f6e91c9bf30cc53e83742d983eec66ff/src/C%2B%2B/Log.h#L115

I took those two examples since they are simpler than the FileLogFactory I believe.

**Comment by McLeodD** [comment]
IMO you should close your issue though.

**Comment by FabioNevesRezende** [comment]
This example is not very clear on how to implement it, for example the class ScreenLog which implements the writing of the log is never referenced inside ScreenLogFactory.. I couldn't make one poc using the examples provided

**Comment by leleftheriades** [comment]
You can provide an implementation of FIX::Log but by that time you get the message already serialized as a string.

	void onIncoming(const std::string& message) override;
	void onOutgoing(const std::string& message) override;
	void onEvent(const std::string& message) override;

I think it's too late, as the message has already been converted, and converting it back to a fix message is expensive

**Comment by FabioNevesRezende** [comment]
Thanks for the help, I override like in the [Filelog](https://github.com/quickfix/quickfix/blob/12ae2153f6e91c9bf30cc53e83742d983eec66ff/src/C%2B%2B/FileLog.h) class to keep the file logging functionality
