### ISSUE TITLE
Sequence number management post logon ACK with ResetSeqNumFlag[141]=Y

### ISSUE THREAD

**Issue by Youssef-amimi** [quickfix/quickfix#562]
I am developing with C++ a trading server with quickfix (version 1.15.1 ) to connect to a stock exchange. I send a logon request with ResetSeqNumFlag(141)=Y. Following this logon request the exchange respond with a Logon Response also with ResetSeqNumFlag(141)=Y. then the trading server send a heartbeat with MsgSeqNum(34) = 2, in which I get a Resend request from the exchange.
This is an extract of the logs:
12:38:30:090 Outgoing: Logon 8=FIXT.1.1|9=123|35=A|34=1|49=TRADER|52=20240307-11:38:30.090|56=EXCHANGE|1128=9|98=0|108=30|141=Y|553=fixfisg5|554=**************|1137=9|10=230|
12:38:35:568  Incoming: Logon 8=FIXT.1.1|9=91|35=A|34=1|49=EXCHANGE|52=20240307-11:38:30.118|56=TRADER|98=0|108=30|141=Y|1137=9|1409=0|10=094|
12:39:00:087  Outgoing: Heart 8=FIXT.1.1|9=59|35=0|34=2|49=TRADER|52=20240307-11:39:00.087|56=EXCHANGE|10=144|
12:39:00:120  Incoming: Resend 8=FIXT.1.1|9=68|35=2|34=2|49=EXCHANGE|52=20240307-11:39:00.114|56=TRADER|7=1|16=0|10=004|

The exchange explained that following the sending of the a Logon ACK with ResetSeqNumFlag(141)=Y, they expected the next message that we send is with MsgSeqNum(34) = 1 not 2.
After I reviewed the FIX protocol documentation and standards (https://www.fixtrading.org/standards/fix-session-layer-online/), particularly the sections related to session management and sequence number, I found that there is 2 sections talking about this situation :
**Using ResetSeqNumFlag(141) to reset FIX session for 24 hour connectivity**
- The peer initiating the FIX session reset should set its NextNumIn to 1 and NextNumOut to 1, then send a Logon(35=A) message with ResetSeqNumFlag(141) set to “Y” and MsgSeqNum(34) set to 1.
- The peer receiving the Logon(35=A) message should set its NextNumIn to 2 and NextNumOut to 1, then send a Logon(35=A) acknowledgement with ResetSeqNumFlag(141) set to “Y” and with MsgSeqNum(24) set of 1.
- Upon completion of the session reset, both peers must have NextNumIn = 2 and NextNumOut = 2.

**Using ResetSeqNumFlag(141) to reset FIX session during FIX connection establishment**
The initiator of a FIX session may reset the FIX session upon initial logon via sending the Logon(35=A) with ResetSeqNumFlag(141) set to “Y”.

As I am in the second situation, I don't know what's the expected behavior. Should the exchange send the Logon response without ResetSeqNumFlag(141)=Y? I wonder why they send it in the first place as I already send it in the logon request (They are also using the quickfix)? if it's ok to send it back in the logon response, should the quickfix in my side reset the sequence numbers to 1 ( I doubt this is the correct answer)? or should they expect the next sequence number to be 2(Does the quickfix do that in the case of the acceptor)?

**Comment by pdm-steve** [comment]
This is the initiator's logging output when connecting two QuickFIX C++ instances while adding 141=Y in the initiator's Logon message:

[FIXOUT]  8=FIX.4.2|9=91|35=A|34=1|49=TEST_INITIATOR|52=20240411-08:18:58.770815|56=TEST_ACCEPTOR|98=0|108=10|141=Y|10=019|
[FIXIN]  8=FIX.4.2|9=91|35=A|34=1|49=TEST_ACCEPTOR|52=20240411-08:18:58.772049|56=TEST_INITIATOR|98=0|108=10|141=Y|10=020|
(QuickFIX) Logon contains ResetSeqNumFlag=Y, reseting sequence numbers to 1
(QuickFIX) Received logon response
[FIXIN]  8=FIX.4.2|9=73|35=0|34=2|49=TEST_ACCEPTOR|52=20240411-08:19:08.781791|56=TEST_INITIATOR|10=192|
[FIXOUT]  8=FIX.4.2|9=73|35=0|34=2|49=TEST_INITIATOR|52=20240411-08:19:08.782241|56=TEST_ACCEPTOR|10=183|


FIX docs say:
"The peer receiving the Logon(35=A) message should set its NextNumIn to 2 and NextNumOut to 1, then send a Logon(35=A) acknowledgement **with ResetSeqNumFlag(141) set to “Y”** and with MsgSeqNum(24) set of 1."
It is a must for the acceptor (exchange) to send back 141=Y, because this is the trigger for the initiator side to reset it's incoming sequence number. So this complies with your examples.

FIX docs say:
"Upon completion of the session reset, both peers must have NextNumIn = 2 and NextNumOut = 2."
Hence the exchange should expect MsgSeqNum(34) = 2 after the Logon message.

**Comment by Youssef-amimi** [comment]
Thank you @pdm-steve, Much appreciated. This totally answers my question. I already forwarded your answer to the concerned Stock exchange, and they are convinced to try to correct this behavior.
