### ISSUE TITLE
String to double conversion precision

### ISSUE THREAD

**Issue by PaxHumana** [quickfix/quickfix#83]
Hi,

The method fast_atof() fails to convert numbers that are possible to represent (with less than 15 digits).
Simple test put the value 1.233, in a double field, when the filed is read again the value 1.2329999999999999 will be returned. Reverting to the old method calling strtod() fixes the issue and 1.233 is returned.

Some might prefer the faster conversion that fsat_atof() offers, but if you have to add rounding on all floating point numbers from QuickFix this performance gain is lost. I suggest to remove fast_atof() and use strtod() again.

**Comment by Ambal** [comment]
Hi, PaxHumana. Good catch actually. It is shame that we have such poor unit test pack for double <> string conversion. The better idea would be to use Google's "double_conversion" project for similar purposes at it offers strtod/printf precision while working significantly faster: https://github.com/google/double-conversion . We will definitely loose some of the performance for string => double deserialization but it is a lesser price to pay rather than doing rounding everywhere.

**Comment by Ambal** [comment]
Should be resolved in https://github.com/Ambal/quickfix/commit/7c938ced126df7e77ef3958f6bca6a2fb7c02818
